const mockuser = {
	login: 'brain-shutdown',
	id: 51878437,
	node_id: 'MDQ6VXNlcjUxODc4NDM3',
	avatar_url: 'https://avatars.githubusercontent.com/u/51878437?v=4',
	gravatar_id: '',
	url: 'https://api.github.com/users/brain-shutdown',
	html_url: 'https://github.com/brain-shutdown',
	followers_url: 'https://api.github.com/users/brain-shutdown/followers',
	following_url: 'https://api.github.com/users/brain-shutdown/following{/other_user}',
	gists_url: 'https://api.github.com/users/brain-shutdown/gists{/gist_id}',
	starred_url: 'https://api.github.com/users/brain-shutdown/starred{/owner}{/repo}',
	subscriptions_url: 'https://api.github.com/users/brain-shutdown/subscriptions',
	organizations_url: 'https://api.github.com/users/brain-shutdown/orgs',
	repos_url: 'https://api.github.com/users/brain-shutdown/repos',
	events_url: 'https://api.github.com/users/brain-shutdown/events{/privacy}',
	received_events_url: 'https://api.github.com/users/brain-shutdown/received_events',
	type: 'User',
	site_admin: false,
	name: 'Andre Pires',
	company: 'Bosch',
	blog: '',
	location: 'Portugal',
	email: null,
	hireable: null,
	bio: "I'm a mechanical engineer and a web development enthusiast! ",
	twitter_username: null,
	public_repos: 39,
	public_gists: 6,
	followers: 0,
	following: 0,
	created_at: '2019-06-16T10:54:12Z',
	updated_at: '2022-01-30T20:19:09Z',
};

export default mockuser;
